### ISSUE TITLE
cfquery is not handled properly

### ISSUE THREAD

**Issue by ryanguill** [foundeo/toscript#1]
``` 
<cfquery name="local.test" result="local.qResult">
select * from myTable 
where x = <cfqueryparam cfsqltype="cf_sql_char" value="#arguments.x#">
order by y ASC
</cfquery>
```
becomes
```
cfquery( name="local.test", result="local.qResult" ) {

writeOutput("select * from myTable 
where x =");
cfqueryparam( cfsqltype="cf_sql_char", value=arguments.x );
writeOutput("order by y ASC");
}
```

**Comment by pfreitag** [comment]
Hey Ryan -- that syntax actually does work on both ACF and Lucee! 

I realize that using `queryExecute` would be better, but for queries that include nested logic I found it pretty complicated to convert.

**Comment by ryanguill** [comment]
my apologies, I never expected that code to work properly!

**Comment by pfreitag** [comment]
No prob!

I will be adding a comment to state that `queryExecute` is preferred syntax. 

Here is a link to a gist on trycf showing that this sort of code does work incase anyone comes across this issue from a search engine, etc: http://trycf.com/gist/996760b766736639d4a8c5bfe9531637/acf11
