### ISSUE TITLE
CFQuery not converting to new query()

### ISSUE THREAD

**Issue by nikhildevre** [foundeo/toscript#21]
Input

` < cfcomponent >
        < cfset variables.n = 10 >
        < cffunction name="init" >
            < cfargument name="number" >
            < cfset variables.n = arguments.number >
            < cfreturn this >
        </cffunction > 
    
		<cffunction name="myQuery" returntype="query">
		    <cfquery name="myQuery" datasource="myDataSource">
		        SELECT 
		            Column1,
		            Column2
                FROM [dbo].[myTable]
		    </cfquery>
			<cfreturn myQuery>
		</cffunction>
		
</cfcomponent>`

OUTPUT

`component {
	variables.n = 10;

	public function init(number) {
		variables.n = arguments.number;
		return this;
	}

	public query function myQuery() {
		cfquery( name="myQuery", datasource="myDataSource" ) { //Note: queryExecute() is the preferred syntax but this syntax is easier to convert generically

			writeOutput("SELECT 
		            Column1,
		            Column2
                FROM [dbo].[myTable]");
		}
		return myQuery;
	}

}
`

**Comment by nikhildevre** [comment]
Nevermind. It works as expected.

**Comment by pfreitag** [comment]
Yes ideally we would use 

```
myQuery = queryExecute("SELECT 
	            Column1,
	            Column2
            FROM [dbo].[myTable]",{}, {datasource="myDataSource"});
```

But that is really hard to do generically if you have a query with cfif statements in the SQL, etc. So using the generic syntax still works in those more complicated cases.
