### ISSUE TITLE
<cfstoredproc> Throwing error

### ISSUE THREAD

**Issue by nikhildevre** [foundeo/toscript#22]
Input
====

`
< cffunction name="myQuery" returntype="query" >
		    
		    <cfstoredproc procedure="Insert_Book" datasource="somedsn"> 
 
                <cfprocparam cfsqltype="cf_sql_varchar" value="sometitle"> 
             
            </cfstoredproc> 
		    
			<cfreturn Insert_Book>
		< /cffunction >
`

Output
=====

`
public query function myQuery() {
		/* toScript ERROR: Unable to convert tag: cfstoredproc to CFML Script

				<cfstoredproc procedure="Insert_Book" datasource="somedsn"> 
 
                <cfprocparam cfsqltype="cf_sql_varchar" value="sometitle"> 
             
            </cfstoredproc>

		*/

		return Insert_Book;
	}

`

**Comment by pfreitag** [comment]
Thanks for reporting this, I will get it fixed.
