### ISSUE TITLE
cfinclude not implemented

### ISSUE THREAD

**Issue by ryanguill** [foundeo/toscript#4]
```
/* toScript ERROR: Unable to convert tag: cfinclude to CFML Script

<cfinclude template="x" />

*/
```

**Comment by pfreitag** [comment]
Fixed, however I noticed that runonce is not implemented in script on Lucee, may have to file a bug for that.

**Comment by pfreitag** [comment]
Bug already logged in Lucee issue tracker: https://luceeserver.atlassian.net/browse/LDEV-983
