### ISSUE TITLE
Unimplemented condition: cfloop on a list

### ISSUE THREAD

**Issue by mjhagen** [foundeo/toscript#6]
This code couldn't be converted:
```
<cfloop list="#defaultSort#" index="orderByPart">
  <cfset orderByString = listAppend( orderByString, "mainEntity.#orderByPart#" ) />
</cfloop>
```
Probably because CF9 doesn't support for..in on lists I think.

**Comment by pfreitag** [comment]
I think that is due to using `index` instead of `item` if so, easy fix
